name: gitartwork from a contribution graph

on:
  push:

jobs:
  build:
    name: Make gitartwork SVG
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jasineri/gitartwork@v1
        with:
          user_name: "kamillsen"
          text: "Hi_Guys"
      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Add gitartwork.svg"
          branch: main  # Eğer farklı bir dal (branch) kullanıyorsanız, burayı değiştirin
